version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3002:3002"
    volumes:
      - ./server:/usr/src/app
      - ./server/data:/app/data
      - backend_node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3002
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_node_modules: